// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWpxdm2SmqL0sn_sAiPoInCQMqXYJjwLk',
    appId: '1:99080311871:android:c141e6203b9e2427f3148a',
    messagingSenderId: '99080311871',
    projectId: 'splitauth-c6d09',
    storageBucket: 'splitauth-c6d09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHzSvQGm14e8-j0cJ2Y-qpstLSU869OIo',
    appId: '1:99080311871:ios:a290b103421adaedf3148a',
    messagingSenderId: '99080311871',
    projectId: 'splitauth-c6d09',
    storageBucket: 'splitauth-c6d09.appspot.com',
    androidClientId: '99080311871-smh7hop8l76ntog9rsei2fsrge6k3b1s.apps.googleusercontent.com',
    iosClientId: '99080311871-k162hn0b5f7ekodtehlr9o3ddf1ns1vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
